name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: Release
    timeout-minutes: 10
    runs-on: ubuntu-latest
    if: github.repository == 'igortrnko/rn-barcode-renderer'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Update npm for Trusted Publishing
        run: npm install -g npm@latest

      - name: Install Dependencies
        run: yarn

      - name: Check Code
        run: yarn check:code

      - name: Build Package
        run: yarn build

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
          commit: Version release
          title: Next release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
